#
# PATHS
#
path_in: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/Gambia/Data/2024/Raw/LGR'
path_out: '/home/cesar/Dropbox/Cesar/PostDoc/Projects/Gambia/Data/2024/Processed'

# Site and variable to process
#
site: 'Gambia'
date: '2024-01-14'
file: 'fgga_2024-01-14_f0000'
variable: 'CH4'

# Location features
#
Air:
  Temp: 35 # Air temperture in °C
  Pres: 1011 # Air pressure in hPa
Chamber:
  Volume: 40 # Volume in Liters
  Area: 0.19 # Area in (m2)

Plot:
  ylim_max:
  ylim_min:
